language:node_ls
node_js:
  - "8"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=andrescortesg -Dsonar.projectKey=andrescortesg.micalc -Dsonar.sources='./app' -X
after_success:
 - npm run coveralls
